/**
 * 内容预处理工具 - 过滤敏感信息避免触发 AI 安全机制
 */

/**
 * 替换内容中的敏感信息
 * 将敏感词替换为安全表述，避免触发 Gemini 等模型的安全拒绝
 */
export function sanitizeAgeContent(content: string): string {
  if (!content) return content;

  let result = content;

  // 中文年龄表述：X岁（X < 18）
  result = result.replace(/\b([1-9]|1[0-7])\s*岁/g, '年轻');
  result = result.replace(/\b0([1-9]|1[0-7])\s*岁/g, '年轻');

  // 英文年龄表述
  result = result.replace(/\b([1-9]|1[0-7])\s*years?\s*old\b/gi, 'young');
  result = result.replace(/\b([1-9]|1[0-7])-year-old\b/gi, 'young');
  result = result.replace(/\bage\s*([1-9]|1[0-7])\b/gi, 'young age');

  // 敏感词替换表
  const sensitiveTerms: [RegExp, string][] = [
    // === 年龄相关 ===
    [/未成年/g, '年轻人'],
    [/小孩子?/g, '年轻人'],
    [/小朋友/g, '年轻人'],
    [/小学生/g, '学生'],
    [/初中生/g, '学生'],
    [/中学生/g, '学生'],
    [/高中生/g, '学生'],
    [/幼女/g, '少女'],
    [/幼童/g, '年轻人'],
    [/儿童/g, '年轻人'],
    [/萝莉/g, '少女'],
    [/正太/g, '少年'],
    [/\bminor[s]?\b/gi, 'young person'],
    [/\bchild(ren)?\b/gi, 'young person'],
    [/\bkid[s]?\b/gi, 'young person'],
    [/\bteen(ager)?[s]?\b/gi, 'young person'],
    [/\bunder\s*age[d]?\b/gi, 'young'],
    [/\bloli\b/gi, 'girl'],
    [/\bshota\b/gi, 'boy'],

    // === 家庭关系敏感词（乱伦相关）===
    [/乱伦/g, '禁忌关系'],
    [/母子/g, '两人'],
    [/父女/g, '两人'],
    [/兄妹/g, '两人'],
    [/姐弟/g, '两人'],
    [/兄弟/g, '两人'],
    [/姐妹/g, '两人'],
    [/母女/g, '两人'],
    [/父子/g, '两人'],
    [/叔侄/g, '两人'],
    [/舅甥/g, '两人'],
    [/继母/g, '女性'],
    [/继父/g, '男性'],
    [/后妈/g, '女性'],
    [/后爸/g, '男性'],
    [/养母/g, '女性'],
    [/养父/g, '男性'],
    [/干妈/g, '女性'],
    [/干爹/g, '男性'],
    [/岳母/g, '女性'],
    [/公公/g, '男性'],
    [/婆婆/g, '女性'],
    [/嫂子/g, '女性'],
    [/小姨子?/g, '女性'],
    [/大姨子?/g, '女性'],
    [/小舅子?/g, '男性'],
    [/大舅子?/g, '男性'],
    [/\bincest\b/gi, 'forbidden relationship'],
    [/\bstep-?mom\b/gi, 'woman'],
    [/\bstep-?dad\b/gi, 'man'],
    [/\bstep-?mother\b/gi, 'woman'],
    [/\bstep-?father\b/gi, 'man'],
    [/\bstep-?sister\b/gi, 'woman'],
    [/\bstep-?brother\b/gi, 'man'],
    [/\bstep-?son\b/gi, 'man'],
    [/\bstep-?daughter\b/gi, 'woman'],

    // === 暴力/非自愿相关 ===
    [/强奸/g, '强制'],
    [/强暴/g, '强制'],
    [/轮奸/g, '侵犯'],
    [/迷奸/g, '侵犯'],
    [/侵犯/g, '亲密'],
    [/猥亵/g, '触碰'],
    [/性侵/g, '侵犯'],
    [/非礼/g, '触碰'],
    [/调戏/g, '挑逗'],
    [/骚扰/g, '打扰'],
    [/\brape[d]?\b/gi, 'take'],
    [/\braped\b/gi, 'taken'],
    [/\braping\b/gi, 'taking'],
    [/\bassault(ed)?\b/gi, 'touch'],
    [/\bmolest(ed)?\b/gi, 'touch'],
    [/\bforce[d]?\b/gi, 'push'],
    [/\bforcing\b/gi, 'pushing'],

    // === 露骨身体部位（中文）===
    [/阴茎/g, '下体'],
    [/阴道/g, '下体'],
    [/阴蒂/g, '敏感处'],
    [/阴唇/g, '私处'],
    [/阴囊/g, '下体'],
    [/睾丸/g, '下体'],
    [/龟头/g, '前端'],
    [/肉棒/g, '分身'],
    [/肉根/g, '分身'],
    [/肉刃/g, '分身'],
    [/鸡巴/g, '分身'],
    [/屌/g, '分身'],
    [/几把/g, '分身'],
    [/jb/gi, '分身'],
    [/阳具/g, '分身'],
    [/性器/g, '私处'],
    [/生殖器/g, '私处'],
    [/子宫/g, '深处'],
    [/宫口/g, '深处'],
    [/花穴/g, '私处'],
    [/肉穴/g, '私处'],
    [/小穴/g, '私处'],
    [/蜜穴/g, '私处'],
    [/菊穴/g, '后庭'],
    [/菊花/g, '后庭'],
    [/肛门/g, '后庭'],
    [/后穴/g, '后庭'],
    [/乳房/g, '胸部'],
    [/乳头/g, '胸前'],
    [/乳尖/g, '胸前'],
    [/乳晕/g, '胸前'],
    [/奶子/g, '胸部'],
    [/奶头/g, '胸前'],
    [/大奶/g, '丰满'],
    [/巨乳/g, '丰满'],
    [/贫乳/g, '娇小'],
    [/屁股/g, '臀部'],
    [/臀瓣/g, '臀部'],
    [/股沟/g, '臀缝'],
    [/会阴/g, '私处'],

    // === 露骨身体部位（英文）===
    [/\bpenis\b/gi, 'member'],
    [/\bcock\b/gi, 'member'],
    [/\bdick\b/gi, 'member'],
    [/\bphallus\b/gi, 'member'],
    [/\bvagina\b/gi, 'entrance'],
    [/\bpussy\b/gi, 'entrance'],
    [/\bcunt\b/gi, 'entrance'],
    [/\bclit(oris)?\b/gi, 'sensitive spot'],
    [/\btesticle[s]?\b/gi, 'parts'],
    [/\bball[s]?\b/gi, 'parts'],
    [/\banus\b/gi, 'rear'],
    [/\bass\b/gi, 'rear'],
    [/\basshole\b/gi, 'rear'],
    [/\bbreast[s]?\b/gi, 'chest'],
    [/\bboob[s]?\b/gi, 'chest'],
    [/\btit[s]?\b/gi, 'chest'],
    [/\bnipple[s]?\b/gi, 'tips'],
    [/\bareola[s]?\b/gi, 'tips'],

    // === 露骨动作（中文）===
    [/性交/g, '结合'],
    [/做爱/g, '亲热'],
    [/交媾/g, '结合'],
    [/交合/g, '结合'],
    [/媾和/g, '结合'],
    [/操/g, '要'],
    [/干/g, '要'],
    [/肏/g, '要'],
    [/草/g, '要'],
    [/艹/g, '要'],
    [/插入/g, '进入'],
    [/抽插/g, '律动'],
    [/抽送/g, '律动'],
    [/抽动/g, '动作'],
    [/顶弄/g, '触碰'],
    [/冲刺/g, '加速'],
    [/射精/g, '释放'],
    [/射了/g, '释放了'],
    [/内射/g, '注入'],
    [/中出/g, '注入'],
    [/颜射/g, '释放'],
    [/口交/g, '服侍'],
    [/口爆/g, '释放'],
    [/深喉/g, '吞入'],
    [/舔弄/g, '亲吻'],
    [/舔舐/g, '亲吻'],
    [/吮吸/g, '品尝'],
    [/吞咽/g, '吞下'],
    [/手淫/g, '抚慰'],
    [/自慰/g, '抚慰'],
    [/撸/g, '抚摸'],
    [/打飞机/g, '抚慰'],
    [/高潮/g, '巅峰'],
    [/潮吹/g, '释放'],
    [/潮喷/g, '释放'],
    [/绝顶/g, '巅峰'],
    [/爽/g, '舒服'],
    [/淫/g, '欲'],
    [/骚/g, '媚'],
    [/浪/g, '放纵'],
    [/荡/g, '放纵'],
    [/贱/g, '顺从'],
    [/婊/g, '女人'],
    [/妓/g, '女人'],
    [/娼/g, '女人'],
    [/勃起/g, '挺立'],
    [/硬了/g, '反应了'],
    [/湿了/g, '有感觉了'],
    [/流水/g, '湿润'],
    [/淫水/g, '液体'],
    [/爱液/g, '液体'],
    [/精液/g, '液体'],
    [/白浊/g, '液体'],

    // === 露骨动作（英文）===
    [/\bfuck(ed|ing)?\b/gi, 'have'],
    [/\bscrew(ed|ing)?\b/gi, 'have'],
    [/\bbang(ed|ing)?\b/gi, 'have'],
    [/\bpound(ed|ing)?\b/gi, 'push'],
    [/\bthrust(ed|ing)?\b/gi, 'move'],
    [/\bpenetrat(e|ed|ing)\b/gi, 'enter'],
    [/\bejaculat(e|ed|ing)\b/gi, 'release'],
    [/\bcum(ming)?\b/gi, 'release'],
    [/\borgasm(ed|ing)?\b/gi, 'peak'],
    [/\bblowjob\b/gi, 'service'],
    [/\bhandjob\b/gi, 'touch'],
    [/\bmasturbat(e|ed|ing)\b/gi, 'touch'],
    [/\berect(ion)?\b/gi, 'aroused'],
    [/\bhard-?on\b/gi, 'aroused'],
    [/\bwet\b/gi, 'excited'],
    [/\bhorny\b/gi, 'excited'],
    [/\baroused\b/gi, 'excited'],
    [/\bslut\b/gi, 'woman'],
    [/\bwhore\b/gi, 'woman'],
    [/\bbitch\b/gi, 'woman'],
    [/\bhooker\b/gi, 'woman'],
    [/\bprostitute\b/gi, 'woman'],

    // === 特殊play/情趣相关 ===
    [/SM/g, '情趣'],
    [/BDSM/gi, '情趣'],
    [/捆绑/g, '束缚'],
    [/绑缚/g, '束缚'],
    [/调教/g, '训练'],
    [/奴隶/g, '服从者'],
    [/主人/g, '支配者'],
    [/女王/g, '女性'],
    [/母狗/g, '她'],
    [/公狗/g, '他'],
    [/发情/g, '激动'],
    [/求欢/g, '渴望'],
    [/凌辱/g, '支配'],
    [/羞辱/g, '羞涩'],
    [/虐待/g, '管教'],
    [/鞭打/g, '管教'],
    [/滴蜡/g, '情趣'],
    [/窒息/g, '紧张'],
    [/3P/gi, '多人'],
    [/群交/g, '多人'],
    [/乱交/g, '多人'],
    [/换妻/g, '交换'],
    [/NTR/gi, '背叛'],
    [/绿帽/g, '背叛'],
    [/出轨/g, '背叛'],
    [/偷情/g, '私会'],
    [/\bbondage\b/gi, 'restraint'],
    [/\bslave\b/gi, 'submissive'],
    [/\bmaster\b/gi, 'dominant'],
    [/\bmistress\b/gi, 'dominant'],
    [/\bthreesome\b/gi, 'group'],
    [/\borgy\b/gi, 'group'],
    [/\bgang\s*bang\b/gi, 'group'],
    [/\bcheating\b/gi, 'betrayal'],
    [/\bcuckold\b/gi, 'betrayal'],

    // === 更多露骨词汇（中文）===
    [/欲望/g, '渴望'],
    [/欲火/g, '热情'],
    [/情欲/g, '感情'],
    [/性欲/g, '欲望'],
    [/肉欲/g, '欲望'],
    [/兽欲/g, '冲动'],
    [/淫欲/g, '欲望'],
    [/色欲/g, '欲望'],
    [/春情/g, '情动'],
    [/春心/g, '心动'],
    [/媚肉/g, '柔软'],
    [/嫩肉/g, '柔软'],
    [/玉体/g, '身体'],
    [/胴体/g, '身体'],
    [/裸体/g, '身体'],
    [/赤裸/g, '坦诚'],
    [/全裸/g, '赤诚'],
    [/半裸/g, '衣衫不整'],
    [/裸露/g, '展现'],
    [/春光/g, '风景'],
    [/走光/g, '暴露'],
    [/露点/g, '暴露'],
    [/露出/g, '展现'],
    [/脱光/g, '褪去'],
    [/扒光/g, '褪去'],
    [/撕开/g, '拉开'],
    [/扯开/g, '拉开'],
    [/揉捏/g, '抚摸'],
    [/揉搓/g, '抚摸'],
    [/把玩/g, '触碰'],
    [/玩弄/g, '触碰'],
    [/蹂躏/g, '触碰'],
    [/亵玩/g, '触碰'],
    [/摩擦/g, '贴近'],
    [/磨蹭/g, '贴近'],
    [/贴合/g, '靠近'],
    [/紧贴/g, '靠近'],
    [/缠绵/g, '亲密'],
    [/交缠/g, '纠缠'],
    [/纠缠/g, '缠绕'],
    [/紧致/g, '紧实'],
    [/紧窄/g, '紧实'],
    [/紧绷/g, '紧张'],
    [/收缩/g, '收紧'],
    [/痉挛/g, '颤抖'],
    [/抽搐/g, '颤抖'],
    [/战栗/g, '颤抖'],
    [/颤栗/g, '颤抖'],
    [/酥麻/g, '舒适'],
    [/麻痒/g, '舒适'],
    [/快感/g, '感觉'],
    [/快意/g, '愉悦'],
    [/销魂/g, '沉醉'],
    [/飘飘欲仙/g, '舒适'],
    [/欲仙欲死/g, '极致'],
    [/极乐/g, '愉悦'],
    [/狂喜/g, '欢愉'],
    [/呻吟/g, '低语'],
    [/娇喘/g, '喘息'],
    [/喘息/g, '呼吸'],
    [/娇吟/g, '低语'],
    [/浪叫/g, '叫声'],
    [/尖叫/g, '叫声'],
    [/哭喊/g, '叫声'],
    [/哀嚎/g, '叫声'],
    [/求饶/g, '请求'],
    [/哭泣/g, '流泪'],
    [/啜泣/g, '流泪'],
    [/抽噎/g, '哽咽'],
    [/挣扎/g, '扭动'],
    [/扭动/g, '动作'],
    [/挺动/g, '动作'],
    [/迎合/g, '配合'],
    [/承受/g, '接受'],
    [/容纳/g, '接受'],
    [/吞没/g, '包容'],
    [/包裹/g, '包围'],
    [/夹紧/g, '收紧'],
    [/绞紧/g, '收紧'],
    [/吸附/g, '贴合'],
    [/吸吮/g, '品味'],
    [/舔食/g, '品尝'],
    [/吞食/g, '吞下'],
    [/含住/g, '含着'],
    [/咬住/g, '咬着'],
    [/叼住/g, '含着'],
    [/亲吻/g, '吻'],
    [/深吻/g, '吻'],
    [/湿吻/g, '吻'],
    [/舌吻/g, '吻'],
    [/热吻/g, '吻'],
    [/拥吻/g, '拥抱'],
    [/搂抱/g, '拥抱'],
    [/抱紧/g, '拥抱'],
    [/撩拨/g, '触碰'],
    [/挑逗/g, '引诱'],
    [/勾引/g, '吸引'],
    [/诱惑/g, '吸引'],
    [/色诱/g, '吸引'],
    [/引诱/g, '吸引'],
    [/媚眼/g, '眼神'],
    [/抛媚眼/g, '使眼色'],
    [/风骚/g, '妩媚'],
    [/妖娆/g, '妩媚'],
    [/妩媚/g, '动人'],
    [/风情/g, '魅力'],
    [/风韵/g, '魅力'],
    [/性感/g, '迷人'],
    [/火辣/g, '热情'],
    [/魅惑/g, '迷人'],
    [/撩人/g, '动人'],

    // === 更多动作词（中文）===
    [/进入/g, '深入'],
    [/没入/g, '进入'],
    [/深入/g, '进入'],
    [/顶入/g, '进入'],
    [/挺入/g, '进入'],
    [/刺入/g, '进入'],
    [/贯穿/g, '穿过'],
    [/贯入/g, '进入'],
    [/侵入/g, '进入'],
    [/填满/g, '充满'],
    [/塞满/g, '充满'],
    [/撑满/g, '充满'],
    [/撑开/g, '打开'],
    [/顶开/g, '推开'],
    [/冲撞/g, '碰撞'],
    [/撞击/g, '碰撞'],
    [/顶撞/g, '触碰'],
    [/摩擦/g, '触碰'],
    [/滑动/g, '移动'],
    [/滑入/g, '进入'],
    [/滑出/g, '离开'],
    [/进出/g, '往复'],
    [/往复/g, '反复'],
    [/律动/g, '节奏'],
    [/抽送/g, '动作'],
    [/挺送/g, '动作'],
    [/耸动/g, '动作'],
    [/摆动/g, '动作'],
    [/扭腰/g, '动作'],
    [/摇摆/g, '动作'],
    [/起伏/g, '波动'],
    [/颠簸/g, '摇晃'],
    [/骑乘/g, '在上'],
    [/跨坐/g, '坐下'],
    [/坐下/g, '落座'],
    [/趴下/g, '俯身'],
    [/跪下/g, '屈膝'],
    [/弯腰/g, '俯身'],
    [/翘起/g, '抬起'],
    [/抬高/g, '举起'],
    [/张开/g, '打开'],
    [/分开/g, '打开'],
    [/岔开/g, '分开'],
    [/掰开/g, '分开'],
    [/拉开/g, '打开'],

    // === 更多英文词汇 ===
    [/\bnaked\b/gi, 'bare'],
    [/\bnude\b/gi, 'bare'],
    [/\bstrip(ped|ping)?\b/gi, 'undress'],
    [/\bundress(ed|ing)?\b/gi, 'change'],
    [/\bexposed\b/gi, 'revealed'],
    [/\bexposing\b/gi, 'revealing'],
    [/\bgrope[d]?\b/gi, 'touch'],
    [/\bgroping\b/gi, 'touching'],
    [/\bfondle[d]?\b/gi, 'touch'],
    [/\bfondling\b/gi, 'touching'],
    [/\bcaress(ed|ing)?\b/gi, 'touch'],
    [/\bstroke[d]?\b/gi, 'touch'],
    [/\bstroking\b/gi, 'touching'],
    [/\brub(bed|bing)?\b/gi, 'touch'],
    [/\bsqueeze[d]?\b/gi, 'hold'],
    [/\bsqueezing\b/gi, 'holding'],
    [/\bsuck(ed|ing)?\b/gi, 'kiss'],
    [/\blick(ed|ing)?\b/gi, 'kiss'],
    [/\bkiss(ed|ing)?\b/gi, 'kiss'],
    [/\bmoan(ed|ing|s)?\b/gi, 'sigh'],
    [/\bgroan(ed|ing|s)?\b/gi, 'sigh'],
    [/\bscream(ed|ing|s)?\b/gi, 'cry'],
    [/\bpant(ed|ing|s)?\b/gi, 'breathe'],
    [/\bgasp(ed|ing|s)?\b/gi, 'breathe'],
    [/\bwhimper(ed|ing|s)?\b/gi, 'whisper'],
    [/\bpleasure[d]?\b/gi, 'feeling'],
    [/\bpleasuring\b/gi, 'touching'],
    [/\becstasy\b/gi, 'joy'],
    [/\bbliss\b/gi, 'happiness'],
    [/\blust(ful)?\b/gi, 'desire'],
    [/\bdesire[d]?\b/gi, 'want'],
    [/\bdesiring\b/gi, 'wanting'],
    [/\bcrave[d]?\b/gi, 'want'],
    [/\bcraving\b/gi, 'wanting'],
    [/\byearn(ed|ing)?\b/gi, 'want'],
    [/\bsexy\b/gi, 'attractive'],
    [/\bsensual\b/gi, 'intimate'],
    [/\berotic\b/gi, 'romantic'],
    [/\bporn(ographic)?\b/gi, 'adult'],
    [/\bxxx\b/gi, 'adult'],
    [/\blewd\b/gi, 'naughty'],
    [/\bdirty\b/gi, 'naughty'],
    [/\bfilthy\b/gi, 'naughty'],
    [/\bkinky\b/gi, 'playful'],
    [/\bpervert(ed)?\b/gi, 'naughty'],
    [/\bnaughty\b/gi, 'playful'],
    [/\bvirgin(ity)?\b/gi, 'first time'],
    [/\bdeflower(ed)?\b/gi, 'first time'],
    [/\bhymen\b/gi, 'barrier'],
    [/\bsemen\b/gi, 'fluid'],
    [/\bsperm\b/gi, 'fluid'],
    [/\bseed\b/gi, 'essence'],
    [/\bjuice[s]?\b/gi, 'fluid'],
    [/\bdrip(ping|ped)?\b/gi, 'flow'],
    [/\bsoaked\b/gi, 'damp'],
    [/\bsoaking\b/gi, 'getting damp'],
    [/\bdrenched\b/gi, 'damp'],
    [/\btight(ness)?\b/gi, 'snug'],
    [/\bloose\b/gi, 'relaxed'],
    [/\bspread\b/gi, 'open'],
    [/\bspreading\b/gi, 'opening'],
    [/\bwide\s*open\b/gi, 'open'],
    [/\benter(ed|ing)?\b/gi, 'go in'],
    [/\binside\b/gi, 'within'],
    [/\bdeep(er|ly)?\b/gi, 'far'],
    [/\bhard(er)?\b/gi, 'firm'],
    [/\bfast(er)?\b/gi, 'quick'],
    [/\brough(ly)?\b/gi, 'intense'],
    [/\bgentle\b/gi, 'soft'],
    [/\bgently\b/gi, 'softly'],
    [/\bslow(ly)?\b/gi, 'gradual'],
    [/\brhythm(ic)?\b/gi, 'pace'],
    [/\btempo\b/gi, 'pace'],
    [/\bclench(ed|ing)?\b/gi, 'grip'],
    [/\bgrip(ped|ping)?\b/gi, 'hold'],
    [/\bwrap(ped|ping)?\b/gi, 'embrace'],
    [/\benvelop(ed|ing)?\b/gi, 'surround'],
    [/\bswallow(ed|ing)?\b/gi, 'take in'],
    [/\bgag(ged|ging)?\b/gi, 'choke'],
    [/\bchoke[d]?\b/gi, 'struggle'],
    [/\bchoking\b/gi, 'struggling'],
    [/\bspank(ed|ing)?\b/gi, 'tap'],
    [/\bslap(ped|ping)?\b/gi, 'tap'],
    [/\bwhip(ped|ping)?\b/gi, 'strike'],
    [/\bbite\b/gi, 'nibble'],
    [/\bbitten\b/gi, 'nibbled'],
    [/\bbiting\b/gi, 'nibbling'],
    [/\bmark(ed|ing)?\b/gi, 'trace'],
    [/\bhickey\b/gi, 'mark'],
    [/\blove\s*bite\b/gi, 'kiss mark'],

    // === 猎奇/血腥相关（中文）===
    [/血/g, '红色'],
    [/血液/g, '液体'],
    [/鲜血/g, '红色液体'],
    [/血迹/g, '痕迹'],
    [/血腥/g, '激烈'],
    [/血肉/g, '身体'],
    [/血泊/g, '地面'],
    [/流血/g, '受伤'],
    [/出血/g, '受伤'],
    [/喷血/g, '喷出'],
    [/溅血/g, '飞溅'],
    [/染血/g, '沾染'],
    [/血染/g, '染红'],
    [/血淋淋/g, '惨烈'],
    [/血肉模糊/g, '受伤严重'],
    [/尸体/g, '身体'],
    [/尸/g, '体'],
    [/死尸/g, '躯体'],
    [/死亡/g, '离开'],
    [/死/g, '倒下'],
    [/死去/g, '离去'],
    [/死掉/g, '消失'],
    [/杀死/g, '击败'],
    [/杀/g, '击败'],
    [/杀害/g, '伤害'],
    [/杀人/g, '伤人'],
    [/杀戮/g, '战斗'],
    [/屠杀/g, '战斗'],
    [/屠/g, '击败'],
    [/弑/g, '击败'],
    [/斩杀/g, '击败'],
    [/斩/g, '砍'],
    [/砍杀/g, '攻击'],
    [/砍/g, '挥'],
    [/刺杀/g, '攻击'],
    [/刺/g, '戳'],
    [/捅/g, '戳'],
    [/戳/g, '碰'],
    [/割/g, '划'],
    [/切割/g, '分开'],
    [/肢解/g, '分离'],
    [/分尸/g, '分离'],
    [/碎尸/g, '破碎'],
    [/断肢/g, '受伤'],
    [/断臂/g, '受伤'],
    [/断腿/g, '受伤'],
    [/断头/g, '分离'],
    [/斩首/g, '分离'],
    [/开膛/g, '打开'],
    [/破腹/g, '打开'],
    [/剖腹/g, '打开'],
    [/挖心/g, '取出'],
    [/掏心/g, '取出'],
    [/挖眼/g, '伤害'],
    [/剜眼/g, '伤害'],
    [/内脏/g, '内部'],
    [/肠子/g, '内部'],
    [/肝脏/g, '器官'],
    [/心脏/g, '心'],
    [/脑浆/g, '液体'],
    [/脑袋/g, '头'],
    [/头颅/g, '头'],
    [/骷髅/g, '骨头'],
    [/骨头/g, '硬物'],
    [/白骨/g, '残骸'],
    [/腐烂/g, '变质'],
    [/腐臭/g, '难闻'],
    [/恶臭/g, '气味'],
    [/溃烂/g, '损坏'],
    [/化脓/g, '感染'],
    [/伤口/g, '痕迹'],
    [/创口/g, '痕迹'],
    [/伤痕/g, '痕迹'],
    [/疤痕/g, '印记'],
    [/烧伤/g, '受伤'],
    [/烫伤/g, '受伤'],
    [/灼伤/g, '受伤'],
    [/冻伤/g, '受伤'],
    [/毒/g, '有害'],
    [/中毒/g, '不适'],
    [/毒药/g, '药物'],
    [/毒素/g, '物质'],

    // === 排泄物相关（中文）===
    [/粪/g, '污物'],
    [/屎/g, '污物'],
    [/大便/g, '排泄'],
    [/排便/g, '如厕'],
    [/拉屎/g, '如厕'],
    [/尿/g, '液体'],
    [/小便/g, '排泄'],
    [/排尿/g, '如厕'],
    [/撒尿/g, '如厕'],
    [/尿液/g, '液体'],
    [/黄金/g, '排泄物'],
    [/圣水/g, '液体'],
    [/失禁/g, '失控'],
    [/漏尿/g, '失控'],
    [/呕吐/g, '不适'],
    [/呕吐物/g, '污物'],
    [/吐/g, '吐出'],
    [/口水/g, '唾液'],
    [/唾液/g, '液体'],
    [/涎水/g, '液体'],
    [/鼻涕/g, '液体'],
    [/眼泪/g, '泪水'],
    [/汗水/g, '汗液'],
    [/汗/g, '液体'],

    // === 窒息/呼吸控制相关 ===
    [/窒息/g, '呼吸困难'],
    [/勒颈/g, '握住脖子'],
    [/勒脖子/g, '握住脖子'],
    [/掐脖子/g, '握住脖子'],
    [/掐住/g, '握住'],
    [/扼住/g, '握住'],
    [/锁喉/g, '控制'],
    [/卡住喉咙/g, '控制'],
    [/喘不过气/g, '呼吸急促'],
    [/呼吸困难/g, '不适'],
    [/缺氧/g, '不适'],
    [/憋气/g, '屏息'],
    [/闷住/g, '捂住'],
    [/捂住/g, '盖住'],

    // === 其他猎奇（中文）===
    [/人彘/g, '惩罚'],
    [/活埋/g, '掩埋'],
    [/活剥/g, '剥离'],
    [/剥皮/g, '剥离'],
    [/炮烙/g, '惩罚'],
    [/凌迟/g, '惩罚'],
    [/车裂/g, '惩罚'],
    [/腰斩/g, '惩罚'],
    [/五马分尸/g, '惩罚'],
    [/满清十大酷刑/g, '惩罚'],
    [/酷刑/g, '惩罚'],
    [/拷打/g, '惩罚'],
    [/拷问/g, '询问'],
    [/折磨/g, '痛苦'],
    [/虐/g, '对待'],
    [/虐待/g, '对待'],
    [/施虐/g, '对待'],
    [/受虐/g, '承受'],
    [/痛苦/g, '难受'],
    [/惨叫/g, '叫声'],
    [/惨/g, '严重'],
    [/凄惨/g, '悲伤'],
    [/悲惨/g, '悲伤'],
    [/残忍/g, '无情'],
    [/残酷/g, '严厉'],
    [/血腥/g, '激烈'],
    [/暴虐/g, '粗暴'],
    [/变态/g, '异常'],
    [/畸形/g, '异常'],
    [/怪物/g, '异类'],
    [/恶魔/g, '黑暗存在'],
    [/魔鬼/g, '黑暗存在'],
    [/地狱/g, '深渊'],
    [/炼狱/g, '苦难'],

    // === 猎奇/血腥相关（英文）===
    [/\bblood(y)?\b/gi, 'red'],
    [/\bbleeding\b/gi, 'hurt'],
    [/\bbleed\b/gi, 'hurt'],
    [/\bgore\b/gi, 'mess'],
    [/\bgory\b/gi, 'messy'],
    [/\bcorpse\b/gi, 'body'],
    [/\bdead\s*body\b/gi, 'body'],
    [/\bcadaver\b/gi, 'body'],
    [/\bdeath\b/gi, 'end'],
    [/\bdead\b/gi, 'fallen'],
    [/\bdie[ds]?\b/gi, 'fall'],
    [/\bdying\b/gi, 'falling'],
    [/\bkill(ed|ing|s)?\b/gi, 'defeat'],
    [/\bmurder(ed|ing|s)?\b/gi, 'harm'],
    [/\bslaughter(ed|ing)?\b/gi, 'battle'],
    [/\bmassacre[d]?\b/gi, 'battle'],
    [/\bexecut(e|ed|ing)\b/gi, 'end'],
    [/\bexecution\b/gi, 'ending'],
    [/\bbehead(ed|ing)?\b/gi, 'separate'],
    [/\bdecapitat(e|ed|ing)\b/gi, 'separate'],
    [/\bdismember(ed|ing)?\b/gi, 'separate'],
    [/\bmutilat(e|ed|ing)\b/gi, 'damage'],
    [/\btorture[d]?\b/gi, 'punish'],
    [/\btorturing\b/gi, 'punishing'],
    [/\bwound(ed|s)?\b/gi, 'hurt'],
    [/\binjur(y|ed|ies)\b/gi, 'hurt'],
    [/\bscar(red|s)?\b/gi, 'mark'],
    [/\bbruise[ds]?\b/gi, 'mark'],
    [/\bcut[s]?\b/gi, 'mark'],
    [/\bstab(bed|bing)?\b/gi, 'poke'],
    [/\bslash(ed|ing)?\b/gi, 'swing'],
    [/\bslice[d]?\b/gi, 'cut'],
    [/\bslicing\b/gi, 'cutting'],
    [/\bgut[s]?\b/gi, 'inside'],
    [/\bintestine[s]?\b/gi, 'inside'],
    [/\borgan[s]?\b/gi, 'part'],
    [/\bskull\b/gi, 'head'],
    [/\bbone[s]?\b/gi, 'structure'],
    [/\bflesh\b/gi, 'body'],
    [/\brot(ted|ting)?\b/gi, 'decay'],
    [/\bdecay(ed|ing)?\b/gi, 'fade'],
    [/\bdecompos(e|ed|ing)\b/gi, 'break down'],
    [/\bpoison(ed|ing|ous)?\b/gi, 'harmful'],
    [/\btoxic\b/gi, 'harmful'],
    [/\bvenom(ous)?\b/gi, 'harmful'],

    // === 排泄物相关（英文）===
    [/\bfeces\b/gi, 'waste'],
    [/\bfecal\b/gi, 'waste'],
    [/\bshit\b/gi, 'waste'],
    [/\bcrap\b/gi, 'waste'],
    [/\bpoop\b/gi, 'waste'],
    [/\burine\b/gi, 'fluid'],
    [/\bpee\b/gi, 'fluid'],
    [/\bpiss\b/gi, 'fluid'],
    [/\bscat\b/gi, 'waste'],
    [/\bwatersports\b/gi, 'play'],
    [/\bgolden\s*shower\b/gi, 'play'],
    [/\bvomit(ed|ing)?\b/gi, 'sick'],
    [/\bpuke[d]?\b/gi, 'sick'],
    [/\bpuking\b/gi, 'being sick'],
    [/\bsaliva\b/gi, 'fluid'],
    [/\bspit(ting)?\b/gi, 'fluid'],
    [/\bdrool(ing)?\b/gi, 'fluid'],
    [/\bsweat(y|ing)?\b/gi, 'moist'],

    // === 窒息相关（英文）===
    [/\basphyxia(tion)?\b/gi, 'breathless'],
    [/\bsuffocate[d]?\b/gi, 'breathless'],
    [/\bsuffocating\b/gi, 'breathless'],
    [/\bstrangle[d]?\b/gi, 'hold'],
    [/\bstrangling\b/gi, 'holding'],
    [/\bchoke[d]?\b/gi, 'gasp'],
    [/\bchoking\b/gi, 'gasping'],
    [/\bbreath\s*play\b/gi, 'play'],
    [/\bauto-?erotic\b/gi, 'self'],

    // === 其他猎奇（英文）===
    [/\bsadis(t|tic|m)\b/gi, 'dominant'],
    [/\bmasochis(t|tic|m)\b/gi, 'submissive'],
    [/\bsnuff\b/gi, 'dark'],
    [/\bnecro(philia)?\b/gi, 'dark'],
    [/\bcannibalis(m|t)?\b/gi, 'dark'],
    [/\bguro\b/gi, 'dark'],
    [/\bryona\b/gi, 'dark'],
    [/\bhardcore\b/gi, 'intense'],
    [/\bextreme\b/gi, 'intense'],
    [/\bbizarre\b/gi, 'unusual'],
    [/\bfreaky\b/gi, 'unusual'],
    [/\bsick\b/gi, 'ill'],
    [/\btwisted\b/gi, 'unusual'],
    [/\bdeviant\b/gi, 'different'],
    [/\bperverse\b/gi, 'unusual'],
    [/\bdemon\b/gi, 'dark being'],
    [/\bdevil\b/gi, 'dark being'],
    [/\bhell\b/gi, 'abyss'],
    [/\bmonster\b/gi, 'creature'],
    [/\bbeast\b/gi, 'creature'],
    [/\binhuman\b/gi, 'unusual'],
  ];

  for (const [pattern, replacement] of sensitiveTerms) {
    result = result.replace(pattern, replacement);
  }

  return result;
}

/**
 * 检查内容是否包含可能触发安全机制的关键词
 */
export function containsSensitiveContent(content: string): boolean {
  if (!content) return false;

  const sensitivePatterns = [
    /\b([1-9]|1[0-7])\s*岁/,
    /\b([1-9]|1[0-7])\s*years?\s*old\b/i,
    /未成年/,
    /\bminor[s]?\b/i,
    /\bchild(ren)?\b/i,
    /幼女|幼童|萝莉|正太/,
    /\bloli\b/i,
    /\bshota\b/i,
  ];

  return sensitivePatterns.some(pattern => pattern.test(content));
}

/**
 * 预处理发送给 AI 的内容
 * @param content 原始内容
 * @param enableFilter 是否启用过滤（可由设置控制）
 */
export function preprocessContent(content: string, enableFilter = true): string {
  if (!enableFilter) return content;
  return sanitizeAgeContent(content);
}
